touch /usr/local/lib/tinygo/src/device/go.mod
touch /usr/local/lib/tinygo/src/device/sam/go.mod
touch /usr/local/lib/tinygo/src/device/arm/go.mod
touch /usr/local/lib/tinygo/src/device/avr/go.mod
touch /usr/local/lib/tinygo/src/device/esp/go.mod
touch /usr/local/lib/tinygo/src/device/kendryte/go.mod
touch /usr/local/lib/tinygo/src/device/nrf/go.mod
touch /usr/local/lib/tinygo/src/device/nxp/go.mod
touch /usr/local/lib/tinygo/src/device/riscv/go.mod
touch /usr/local/lib/tinygo/src/device/rp/go.mod
touch /usr/local/lib/tinygo/src/device/sifive/go.mod
touch /usr/local/lib/tinygo/src/device/stm32/go.mod
touch /usr/local/lib/tinygo/src/internal/reflectlite/go.mod
touch /usr/local/lib/tinygo/src/internal/task/go.mod
touch /usr/local/lib/tinygo/src/machine/go.mod
touch /usr/local/lib/tinygo/src/os/go.mod
touch /usr/local/lib/tinygo/src/reflect/go.mod
touch /usr/local/lib/tinygo/src/runtime/go.mod
touch /usr/local/lib/tinygo/src/runtime/interrupt/go.mod
touch /usr/local/lib/tinygo/src/runtime/volatile/go.mod
touch /usr/local/lib/tinygo/src/sync/go.mod
touch /usr/local/lib/tinygo/src/testing/go.mod
