name: CI
on:
  push:
    branches:
      - master
jobs:
  build:
    name:  Semantic Versioning
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - name: Repo Checkout
        uses: actions/checkout@v2
      - name: Semantic Release
        run: |
          docker run --rm -e GITHUB_TOKEN=${GITHUB_TOKEN} -v "${PWD}":/app michcald/semantic-release
